language: perl
perl:
  - 5.12
  - 5.14
  - 5.16
script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Coveralls
  - cover -delete 
  - perl Build.PL && ./Build build && HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,inc" PERL5LIB="lib" prove t/model 
after_success:
  - cover -report coveralls

